import {
  Capability,
  ProviderType,
  SpeedTier,
  Availability,
} from "./modelTypes";

export const modelCatalog = Object.freeze([
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b",
    displayName: "Nemotron 3 Ultra",
    provider: "nvidia",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.LONG_CONTEXT,
      Capability.AGENTIC,
    ],
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    vision: false,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: false,
    speed: SpeedTier.MEDIUM,
    availability: Availability.HIGH,
    free: true,
    deprecated: false,
    priority: 1,
    notes: "1M context, 550B MoE (55B active), hybrid Transformer-Mamba, frontier reasoning and orchestration",
  },
  {
    id: "nvidia/nemotron-3-super-120b-a12b",
    displayName: "Nemotron 3 Super",
    provider: "nvidia",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.AGENTIC,
    ],
    contextWindow: 262144,
    maxOutputTokens: 65536,
    vision: false,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: false,
    speed: SpeedTier.MEDIUM,
    availability: Availability.HIGH,
    free: true,
    deprecated: false,
    priority: 2,
    notes: "262K context, 120B MoE (12B active), strong general reasoning and agent tasks",
  },
  {
    id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
    displayName: "Nemotron 3 Nano Omni",
    provider: "nvidia",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.VISION,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.MULTIMODAL,
      Capability.VIDEO,
      Capability.AUDIO,
    ],
    contextWindow: 256000,
    maxOutputTokens: 16384,
    vision: true,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: true,
    speed: SpeedTier.MEDIUM,
    availability: Availability.MEDIUM,
    free: true,
    deprecated: false,
    priority: 3,
    notes: "256K context, 30B MoE, multimodal (image/audio/video), extended thinking with 16K reasoning budget",
  },
  {
    id: "nvidia/nemotron-nano-9b-v2",
    displayName: "Nemotron Nano 9B v2",
    provider: "nvidia",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.REASONING,
      Capability.FAST,
    ],
    contextWindow: 128000,
    maxOutputTokens: 16384,
    vision: false,
    coding: false,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: false,
    speed: SpeedTier.VERY_FAST,
    availability: Availability.HIGH,
    free: true,
    deprecated: false,
    priority: 4,
    notes: "128K context, 9B params, very fast inference, lightweight general tasks",
  },
  {
    id: "nvidia/nemotron-nano-12b-v2-vl",
    displayName: "Nemotron Nano 12B v2 VL",
    provider: "nvidia",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.VISION,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.REASONING,
      Capability.MULTIMODAL,
      Capability.VIDEO,
      Capability.DOCUMENT_INTELLIGENCE,
    ],
    contextWindow: 128000,
    maxOutputTokens: 16384,
    vision: true,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: true,
    speed: SpeedTier.FAST,
    availability: Availability.MEDIUM,
    free: true,
    deprecated: false,
    priority: 5,
    notes: "128K context, hybrid Transformer-Mamba, video understanding and document intelligence",
  },
  {
    id: "nvidia/nemotron-3.5-content-safety",
    displayName: "Nemotron 3.5 Content Safety",
    provider: "nvidia",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.VISION,
      Capability.MULTIMODAL,
    ],
    contextWindow: 128000,
    maxOutputTokens: 8192,
    vision: true,
    coding: false,
    structuredOutput: false,
    toolCalling: false,
    reasoning: false,
    multimodal: true,
    speed: SpeedTier.FAST,
    availability: Availability.LOW,
    free: true,
    deprecated: false,
    priority: 13,
    notes: "128K context, specialized for content safety classification (text + image only)",
  },
  {
    id: "google/gemma-4-26b-a4b-it",
    displayName: "Gemma 4 26B A4B IT",
    provider: "google",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.VISION,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.MULTIMODAL,
      Capability.VIDEO,
    ],
    contextWindow: 262144,
    maxOutputTokens: 65536,
    vision: true,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: true,
    speed: SpeedTier.MEDIUM,
    availability: Availability.MEDIUM,
    free: true,
    deprecated: false,
    priority: 6,
    notes: "262K context, 25.2B total (3.8B active MoE), image + video (up to 60s at 1fps), native function calling, configurable thinking",
  },
  {
    id: "google/gemma-4-31b-it",
    displayName: "Gemma 4 31B IT",
    provider: "google",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.VISION,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.MULTIMODAL,
      Capability.VIDEO,
    ],
    contextWindow: 262144,
    maxOutputTokens: 65536,
    vision: true,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: true,
    speed: SpeedTier.MEDIUM,
    availability: Availability.MEDIUM,
    free: true,
    deprecated: false,
    priority: 7,
    notes: "262K context, 31B params, image + video (up to 60s at 1fps), native function calling, configurable thinking",
  },
  {
    id: "poolside/laguna-s-2.1",
    displayName: "Laguna S 2.1",
    provider: "poolside",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.AGENTIC,
    ],
    contextWindow: 262144,
    maxOutputTokens: 65536,
    vision: false,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: false,
    speed: SpeedTier.MEDIUM,
    availability: Availability.MEDIUM,
    free: true,
    deprecated: false,
    priority: 8,
    notes: "262K context, 118B total (8B active MoE), 70.2% Terminal-Bench, 40.4% DeepSWE, strong coding agent",
  },
  {
    id: "poolside/laguna-xs-2.1",
    displayName: "Laguna XS 2.1",
    provider: "poolside",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.AGENTIC,
      Capability.FAST,
    ],
    contextWindow: 262144,
    maxOutputTokens: 32768,
    vision: false,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: false,
    speed: SpeedTier.FAST,
    availability: Availability.MEDIUM,
    free: true,
    deprecated: false,
    priority: 9,
    notes: "262K context, 33B MoE (compact), FP8 quantized, fast coding agent workflows",
  },
  {
    id: "cohere/north-mini-code",
    displayName: "North Mini Code",
    provider: "cohere",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.AGENTIC,
      Capability.FAST,
    ],
    contextWindow: 256000,
    maxOutputTokens: 65536,
    vision: false,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: false,
    speed: SpeedTier.FAST,
    availability: Availability.MEDIUM,
    free: true,
    deprecated: false,
    priority: 10,
    notes: "256K context, 30B total (3B active MoE), native JSON schema interleaved reasoning, agentic coding",
  },
  {
    id: "inclusionai/ling-3.0-flash",
    displayName: "Ling 3.0 Flash",
    provider: "inclusionai",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.FAST,
    ],
    contextWindow: 262144,
    maxOutputTokens: 65536,
    vision: false,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: false,
    speed: SpeedTier.FAST,
    availability: Availability.HIGH,
    free: true,
    deprecated: false,
    priority: 11,
    notes: "262K context, 1.3B active (7.9B total MoE), fast instruction following, switchable thinking and instant modes",
  },
  {
    id: "openai/gpt-oss-20b",
    displayName: "GPT-OSS 20B",
    provider: "openai",
    providerType: ProviderType.OPENROUTER,
    capabilities: [
      Capability.TEXT,
      Capability.CODE,
      Capability.REASONING,
      Capability.STRUCTURED_OUTPUT,
      Capability.TOOL_CALLING,
      Capability.FAST,
    ],
    contextWindow: 131072,
    maxOutputTokens: 65536,
    vision: false,
    coding: true,
    structuredOutput: true,
    toolCalling: true,
    reasoning: true,
    multimodal: false,
    speed: SpeedTier.FAST,
    availability: Availability.HIGH,
    free: true,
    deprecated: false,
    priority: 12,
    notes: "131K context, 21B total (3.6B active MoE), Harmony response format, fine-tunable, agentic capabilities",
  },
]);

export default modelCatalog;
