export const STRATEGY = {
  FULL_GENERATION: "FULL_GENERATION",
  EDIT_EXISTING: "EDIT_EXISTING",
  INSERT_SECTION: "INSERT_SECTION",
  DELETE_COMPONENT: "DELETE_COMPONENT",
  STYLE_UPDATE: "STYLE_UPDATE",
  LAYOUT_UPDATE: "LAYOUT_UPDATE",
  CONTENT_UPDATE: "CONTENT_UPDATE",
  IMAGE_GENERATION: "IMAGE_GENERATION",
  VOICE_COMMAND: "VOICE_COMMAND",
};

export const EXECUTION_TYPE = {
  FAST: "fast",
  NORMAL: "normal",
  HEAVY: "heavy",
};

export const COMPLEXITY = {
  SIMPLE: "simple",
  MEDIUM: "medium",
  COMPLEX: "complex",
};

export const PROVIDER_MODE = {
  AUTO: "auto",
  MANUAL: "manual",
};

export const CAPABILITY = {
  FAST: "fast",
  FASTEST: "fastest",
  VISION: "vision",
  VOICE: "voice",
  JSON: "json",
  MULTI_MODEL: "multi_model",
  PREMIUM: "premium",
};

export const INTENT_TO_STRATEGY = {
  generate: STRATEGY.FULL_GENERATION,
  edit: STRATEGY.EDIT_EXISTING,
  insert: STRATEGY.INSERT_SECTION,
  delete: STRATEGY.DELETE_COMPONENT,
  style: STRATEGY.STYLE_UPDATE,
  layout: STRATEGY.LAYOUT_UPDATE,
  content: STRATEGY.CONTENT_UPDATE,
  image: STRATEGY.IMAGE_GENERATION,
  voice: STRATEGY.VOICE_COMMAND,
};

export const STRATEGY_COMPLEXITY = {
  [STRATEGY.FULL_GENERATION]: COMPLEXITY.COMPLEX,
  [STRATEGY.EDIT_EXISTING]: COMPLEXITY.MEDIUM,
  [STRATEGY.INSERT_SECTION]: COMPLEXITY.MEDIUM,
  [STRATEGY.DELETE_COMPONENT]: COMPLEXITY.SIMPLE,
  [STRATEGY.STYLE_UPDATE]: COMPLEXITY.SIMPLE,
  [STRATEGY.LAYOUT_UPDATE]: COMPLEXITY.MEDIUM,
  [STRATEGY.CONTENT_UPDATE]: COMPLEXITY.SIMPLE,
  [STRATEGY.IMAGE_GENERATION]: COMPLEXITY.COMPLEX,
  [STRATEGY.VOICE_COMMAND]: COMPLEXITY.MEDIUM,
};

export const STRATEGY_EXECUTION = {
  [STRATEGY.FULL_GENERATION]: EXECUTION_TYPE.HEAVY,
  [STRATEGY.EDIT_EXISTING]: EXECUTION_TYPE.NORMAL,
  [STRATEGY.INSERT_SECTION]: EXECUTION_TYPE.NORMAL,
  [STRATEGY.DELETE_COMPONENT]: EXECUTION_TYPE.FAST,
  [STRATEGY.STYLE_UPDATE]: EXECUTION_TYPE.FAST,
  [STRATEGY.LAYOUT_UPDATE]: EXECUTION_TYPE.NORMAL,
  [STRATEGY.CONTENT_UPDATE]: EXECUTION_TYPE.FAST,
  [STRATEGY.IMAGE_GENERATION]: EXECUTION_TYPE.HEAVY,
  [STRATEGY.VOICE_COMMAND]: EXECUTION_TYPE.NORMAL,
};

export const STRATEGY_STEPS = {
  [STRATEGY.FULL_GENERATION]: 4,
  [STRATEGY.EDIT_EXISTING]: 3,
  [STRATEGY.INSERT_SECTION]: 2,
  [STRATEGY.DELETE_COMPONENT]: 1,
  [STRATEGY.STYLE_UPDATE]: 1,
  [STRATEGY.LAYOUT_UPDATE]: 2,
  [STRATEGY.CONTENT_UPDATE]: 1,
  [STRATEGY.IMAGE_GENERATION]: 3,
  [STRATEGY.VOICE_COMMAND]: 2,
};

export const REQUIRED_CAPABILITY = {
  [STRATEGY.IMAGE_GENERATION]: CAPABILITY.VISION,
  [STRATEGY.VOICE_COMMAND]: CAPABILITY.VOICE,
};
